feature/auth
sydnenaal/time-manager pull request #3
Opened 2021-07-11 20:24 UTC by Moroyzik

- [ ] added test for Button and Form

2021-07-13 06:45 UTC, sydnenaal requested changes

2021-07-13 06:45 UTC, sydnenaal commented on frontend/src/Components/Atoms/Input/Input.tsx
> +const Input: React.FC<InputProps> = ({ onChange, value, ...rest }) => {
Кнопка и инпут различаются по код-стайлу. 
Сделай типизацию как в кнопке и оберни в мемо. 
Также у кнопки и инпута пропиши `displayName`

2021-07-13 06:45 UTC, sydnenaal commented on frontend/src/Components/Atoms/Input/Input.tsx
> +            onChange={({ target: { value } }) => onChange(value)}
Не надо так делать. Просто прокинь колбэк `onChange` в проп и все.

2021-07-13 06:45 UTC, sydnenaal commented on frontend/src/Components/Atoms/Input/interface.ts
> +    onChange: (value: string) => void
Тут, соответственно, надо поменять сигнатуру. Теперь в аргумент будет приходить `event`.

2021-07-13 06:45 UTC, sydnenaal commented on frontend/src/Components/Atoms/Button/interface.ts
> +import { ReactNode } from 'react'
Не красиво по неймингу выходит. Давай именовать такие файлы как-нибудь так: `[Component].types.ts`

2021-07-13 06:45 UTC, sydnenaal commented on frontend/src/Components/Molecules/AuthForm/__tests__/AuthForm.spec.tsx
> +    let container: HTMLDivElement | null = null
Зачем здесь контейнер и все остальное к нему?
Без него не работает?
Постарайся убрать это.

2021-07-13 12:33 UTC, Moroyzik commented on frontend/src/Components/Atoms/Input/interface.ts
> +    onChange: (value: string) => void
onChange: (event: { target: { value }: string }) => void
такой интерфейс же норм?

2021-07-13 12:43 UTC, sydnenaal commented on frontend/src/Components/Atoms/Input/interface.ts
> +    onChange: (value: string) => void
Нет, хуйня. Для описания события ввода можно импортировать из реакта специальный тип.
Используй `FormEvent<HTMLInputElement>` или `ChangeEvent<HTMLInputElement>`.
Изучи, чем они отличаются, и заюзай тот, который больше всего нам тут подходит.
Если возникнут затруднения, можешь остановиться на `ChangeEvent<HTMLInputElement>`

2021-07-14 06:47 UTC, sydnenaal requested changes

2021-07-14 06:47 UTC, sydnenaal commented on frontend/src/Components/Atoms/Button/Button.styles.ts
> +export const StyledButton = styled.button<StyleButtonProps>`
нужно добавить `min-width` и `min-height`

2021-07-14 21:58 UTC, sydnenaal commented on frontend/src/Components/Atoms/Input/__tests__/Input.spec.tsx
> +        render(<Input value={'test'} onChange={() => event} type={'email'} />)
Очень странная логика. 
Почему хэндлер `onChange` возвращает колбэк? 
Ты ведь прописывал ему сигнатуру `(e: ChangeEvent<HTMLInputElement>) => void`
Более того, это ни на что не влияет. Этот хэндлер нигде ниже не проверяется. Складывается вопрос: зачем он тогда тут?
Либо удали совсем, либо пропиши логичный тест для него, и исправь сигнатуру соответственно.

2021-07-14 22:00 UTC, sydnenaal requested changes

2021-07-14 22:00 UTC, sydnenaal commented on frontend/src/Components/Atoms/Input/__tests__/Input.spec.tsx
> +        render(<Input value={'test@mail.com'} onChange={() => event} type={'email'} />)
Зачем оборачивать строковые пропсы в скобки? Это преттир что ли так делает у нас?

2021-07-14 22:43 UTC, sydnenaal requested changes

2021-07-14 22:43 UTC, sydnenaal commented on frontend/src/Components/Molecules/AuthForm/AuthForm.tsx
> +                    {errors.name &&
`{errors.name && <div>{errors.name}</div>}`

2021-07-14 22:43 UTC, sydnenaal commented on frontend/src/Components/Molecules/AuthForm/AuthForm.tsx
> +            onSubmit={(values, actions) => {
Вынеси это в хэндлер в компоненте

2021-07-17 13:53 UTC, sydnenaal requested changes

2021-07-17 13:53 UTC, sydnenaal commented on frontend/src/Components/Molecules/AuthForm/AuthForm.tsx
> +    const handleOnSubmit = (values: FormikValues, actions: FormikHelpers<FormikValues>) => {
useCallback

2021-07-17 13:53 UTC, sydnenaal commented on frontend/src/Components/Molecules/AuthForm/AuthForm.tsx
> +            initialValues={{ name: 'Dima' }}
Либо за пределы компонента вынеси, либо в useMemo положи. Такая запись убивает оптимизацию ререндеров формы.

2021-07-17 19:30 UTC, sydnenaal approved these changes

2021-07-17 23:02 UTC, closed without merging